author: pauhull
name: CandyCane
version: 1.0
main: de.pauhull.candycane.CandyCane

softdepend: [Friends]

commands:
  perks:
  perk:
  trash:
  bodysee:
  giveall:
  ga:
  vote:
  navigator:
  nav:
  rand: