author: pauhull
name: CandyCane
version: 1.0
main: de.pauhull.candycane.CandyCane

softdepend: [ Votifier ]

commands:
  perks:
  perk:
  trash:
  bodysee:
  giveall:
  tafk:
  verlosung:
  ga:
  vote:
  navigator:
  nav:
  rand:
  fly: